# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=170)),
                ('ativo_imobilizado', models.PositiveIntegerField()),
                ('serial_number', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=12)),
                ('data_retirada', models.DateTimeField()),
                ('data_entrega', models.DateTimeField(default=django.utils.timezone.now)),
                ('localizacao', models.CharField(max_length=150)),
                ('observacoes', models.TextField()),
            ],
        ),
    ]
