# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='fabricante',
            field=models.CharField(default=None, max_length=90),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='ativo_imobilizado',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='data_entrega',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='data_retirada',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='localizacao',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='observacoes',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='serial_number',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(default=None, max_length=12),
        ),
    ]
