# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0002_auto_20170929_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='ativo_imobilizado',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='data_entrega',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='data_retirada',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='fabricante',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='localizacao',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='observacoes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='serial_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
