# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0004_auto_20170929_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(max_length=12),
        ),
    ]
