# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0005_auto_20170929_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
