# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0006_equipamento_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='data_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='data_retirada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
