# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0009_auto_20170930_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='tipo',
            field=models.CharField(choices=[('Notebook', 'Notebook'), ('Desktop', 'Desktop'), ('Projetor', 'Projetor'), ('Impressora', 'Impressora'), ('Monitor', 'Monitor'), ('Periféricos', 'Periféricos'), ('Consumíveis', 'Consumíveis')], default='Notebook', max_length=50),
        ),
    ]
