# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0010_auto_20171002_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
