# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0011_auto_20171009_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='data_entrega',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='data_retirada',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='localizacao',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='prateleira',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='ativo_imobilizado',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='fabricante',
            field=models.CharField(default=None, max_length=90),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='serial_number',
            field=models.CharField(default=None, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='tipo',
            field=models.CharField(choices=[('Notebook', 'Notebook'), ('Desktop', 'Desktop'), ('Projetor', 'Projetor'), ('Impressora', 'Impressora'), ('Monitor', 'Monitor')], default='Notebook', max_length=50),
        ),
    ]
