# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0012_auto_20171009_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Consumíveis', 'Consumíveis'), ('Periféricos', 'Periféricos')], default='Consumíveis', max_length=12)),
                ('item', models.CharField(max_length=170)),
                ('fabricante', models.CharField(default=None, max_length=90)),
                ('quantidade', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Disponivel', ' Disponível'), ('Indisponivel', 'Indisponível')], default='Disponivel', max_length=12)),
                ('prateleira', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('Disponivel', 'Disponível'), ('Indisponivel', 'Indisponível')], default='Disponivel', max_length=12),
        ),
    ]
