# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0016_auto_20171009_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('equipamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='almoxarifado.Equipamento')),
                ('memoria', models.PositiveIntegerField(default=0)),
                ('processador', models.CharField(max_length=170)),
                ('HD', models.PositiveIntegerField(default=0)),
            ],
            bases=('almoxarifado.equipamento',),
        ),
    ]
