# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0022_auto_20171018_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=90)),
            ],
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='fabricante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almoxarifado.Fabricante'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tipo',
            field=models.CharField(choices=[('Consumíveis', 'Consumíveis'), ('Periféricos', 'Periféricos')], default='Consumíveis', max_length=12),
        ),
    ]
