# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0025_auto_20171018_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.CharField(max_length=170),
        ),
    ]
