# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0027_auto_20171020_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='modelo',
            field=models.CharField(max_length=170, unique=True),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='tipo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tipo_itens',
            name='tipo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
