# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0028_auto_20171020_2006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tipo_Itens',
            new_name='TipoItens',
        ),
    ]
